name: build_android_kernel

on:
  watch:
    types: [started]
    
env:
  KERNEL_SOURCE_URL: https://github.com/MiCode/Xiaomi_Kernel_OpenSource/
  KERNEL_SOURCE_BRANCH: dipper-q-oss
  DEFCONFIG_NAME: dipper_user_defconfig
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      
       - name: Clean Up
         run: |
           docker rmi `docker images -q`
           sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
           sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
           sudo -E apt-get update
           sudo -E apt-get -y autoremove --purge
           sudo -E apt-get clean 
           
       - name: Initialization environment
         run: |
            sudo -E apt-get -qq update
            sudo apt-get install bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev

       - name: Clone Build ToolChain
         run: |
            cd ~
            git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9.git Toolchain
         
       - name: Clone Kernel Source Code
         run: |
            cd ~
            git clone $KERNEL_SOURCE_URL -b $KERNEL_SOURCE_BRANCH Kernel
       
       - name: Make Kernel
         run: |
            cd ~/Kernel
            export ARCH=arm64
            export SUBARCH=arm64
            export CROSS_COMPILE=aarch64-linux-android-
            export PATH=~/Toolchain/bin
            make $DEFCONFIG_NAME
            make
